export const products = [
  // Coffee
  {
    id: 1,
    name: "Espresso",
    category: "Coffee",
    price: 3.99,
    image: "img expresso.jpg",
    description: "Strong coffee shot",
  },
  {
    id: 2,
    name: "Cappuccino",
    category: "Coffee",
    price: 4.99,
    image: "img/cappucino.png",
    description: "Coffee with milk foam",
  },
  {
    id: 3,
    name: "Latte",
    category: "Coffee",
    price: 4.99,
    image: "img/latte.webp",
    description: "Coffee with steamed milk",
  },
  {
    id: 4,
    name: "Americano",
    category: "Coffee",
    price: 3.99,
    image: "img/americano.jpg",
    description: "Coffee with hot water",
  },
  {
    id: 5,
    name: "Mocha",
    category: "Coffee",
    price: 5.49,
    image: "img/mocha.webp",
    description: "Coffee with chocolate",
  },
  {
    id: 15,
    name: "Flat White",
    category: "Coffee",
    price: 4.5,
    image: "img/flatwhite.jpg",
    description: "Espresso with steamed milk, less foam",
  },
  {
    id: 16,
    name: "Macchiato",
    category: "Coffee",
    price: 3.75,
    image: "img/macchiato.jpg",
    description: "Espresso with a dollop of foam",
  },

  // Cakes
  {
    id: 6,
    name: "Chocolate Cake",
    category: "Cakes",
    price: 5.99,
    image: "img/chocolatecake.jpg",
    description: "Rich chocolate cake",
  },
  {
    id: 7,
    name: "Cheesecake",
    category: "Cakes",
    price: 5.99,
    image: "img/cheesecake.jpg",
    description: "Creamy cheesecake",
  },
  {
    id: 8,
    name: "Carrot Cake",
    category: "Cakes",
    price: 5.99,
    image: "img/carrotcake.jpg",
    description: "Moist carrot cake",
  },
  {
    id: 9,
    name: "Red Velvet",
    category: "Cakes",
    price: 6.49,
    image: "img/redvelvet.avif",
    description: "Classic red velvet cake",
  },
  {
    id: 17,
    name: "Lemon Tart",
    category: "Cakes",
    price: 5.75,
    image: "img/lemontart.jpg",
    description: "Tangy and sweet lemon tart",
  },
  {
    id: 18,
    name: "Banana Bread",
    category: "Cakes",
    price: 4.99,
    image: "img/bananabread.jpg",
    description: "Moist banana bread loaf",
  },

  // Snacks
  {
    id: 10,
    name: "Croissant",
    category: "Snacks",
    price: 2.99,
    image: "img/croissant.png",
    description: "Buttery croissant",
  },
  {
    id: 11,
    name: "Sandwich",
    category: "Snacks",
    price: 6.99,
    image: "img/sandwich.jpg",
    description: "Fresh sandwich",
  },
  {
    id: 12,
    name: "Muffin",
    category: "Snacks",
    price: 3.49,
    image: "img/muffin.avif",
    description: "Freshly baked muffin",
  },
  {
    id: 13,
    name: "Cookies",
    category: "Snacks",
    price: 2.49,
    image: "img/cookie.avif",
    description: "Homemade cookies",
  },
  {
    id: 14,
    name: "Brownie",
    category: "Snacks",
    price: 3.99,
    image: "img/brownie.jpg",
    description: "Chocolate brownie",
  },
  {
    id: 19,
    name: "Pretzel",
    category: "Snacks",
    price: 2.99,
    image: "img/pretzel.webp",
    description: "Soft salted pretzel",
  },
  {
    id: 20,
    name: "Granola Bar",
    category: "Snacks",
    price: 1.99,
    image: "img/granola.jpg",
    description: "Healthy granola bar",
  },

  // Tea
  {
    id: 21,
    name: "Green Tea",
    category: "Tea",
    price: 3.5,
    image: "img/greentea.jpg",
    description: "Refreshing green tea",
  },
  {
    id: 22,
    name: "Black Tea",
    category: "Tea",
    price: 3.0,
    image: "img/blacktea.webp",
    description: "Classic black tea",
  },
  {
    id: 23,
    name: "Chai Latte",
    category: "Tea",
    price: 4.25,
    image: "img/Chai-Latte.webp",
    description: "Spiced tea with steamed milk",
  },
  {
    id: 24,
    name: "Affogato",
    category: "Coffee",
    price: 5.99,
    image: "img/affogato.jpg",
    description: "Vanilla ice cream topped with hot espresso.",
  },
];
